// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eggroll/meta-service.proto

package com.webank.ai.eggroll.api.framework.meta.service;

public final class MetaService {
  private MetaService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032eggroll/meta-service.proto\0220com.webank" +
      ".ai.eggroll.api.framework.meta.service\032\030" +
      "eggroll/basic-meta.proto2\360\r\n\022StorageMeta" +
      "Service\022h\n\013createTable\022+.com.webank.ai.e" +
      "ggroll.api.core.CallRequest\032,.com.webank" +
      ".ai.eggroll.api.core.CallResponse\022p\n\023cre" +
      "ateTableIfAbsent\022+.com.webank.ai.eggroll" +
      ".api.core.CallRequest\032,.com.webank.ai.eg" +
      "groll.api.core.CallResponse\022h\n\013updateTab" +
      "le\022+.com.webank.ai.eggroll.api.core.Call" +
      "Request\032,.com.webank.ai.eggroll.api.core" +
      ".CallResponse\022t\n\027createFragmentsForTable" +
      "\022+.com.webank.ai.eggroll.api.core.CallRe" +
      "quest\032,.com.webank.ai.eggroll.api.core.C" +
      "allResponse\022k\n\016updateFragment\022+.com.weba" +
      "nk.ai.eggroll.api.core.CallRequest\032,.com" +
      ".webank.ai.eggroll.api.core.CallResponse" +
      "\022i\n\014getTableById\022+.com.webank.ai.eggroll" +
      ".api.core.CallRequest\032,.com.webank.ai.eg" +
      "groll.api.core.CallResponse\022e\n\010getTable\022" +
      "+.com.webank.ai.eggroll.api.core.CallReq" +
      "uest\032,.com.webank.ai.eggroll.api.core.Ca" +
      "llResponse\022f\n\tgetTables\022+.com.webank.ai." +
      "eggroll.api.core.CallRequest\032,.com.weban" +
      "k.ai.eggroll.api.core.CallResponse\022l\n\017ge" +
      "tFragmentById\022+.com.webank.ai.eggroll.ap" +
      "i.core.CallRequest\032,.com.webank.ai.eggro" +
      "ll.api.core.CallResponse\022r\n\025getFragments" +
      "ByTableId\022+.com.webank.ai.eggroll.api.co" +
      "re.CallRequest\032,.com.webank.ai.eggroll.a" +
      "pi.core.CallResponse\022u\n\030getStorageNodesB" +
      "yTableId\022+.com.webank.ai.eggroll.api.cor" +
      "e.CallRequest\032,.com.webank.ai.eggroll.ap" +
      "i.core.CallResponse\022r\n\025getEggNodeManager" +
      "ByIp\022+.com.webank.ai.eggroll.api.core.Ca" +
      "llRequest\032,.com.webank.ai.eggroll.api.co" +
      "re.CallResponse\022h\n\013getNodeById\022+.com.web" +
      "ank.ai.eggroll.api.core.CallRequest\032,.co" +
      "m.webank.ai.eggroll.api.core.CallRespons" +
      "e\022j\n\rgetNodesByIds\022+.com.webank.ai.eggro" +
      "ll.api.core.CallRequest\032,.com.webank.ai." +
      "eggroll.api.core.CallResponse\022m\n\020getNode" +
      "sOfStatus\022+.com.webank.ai.eggroll.api.co" +
      "re.CallRequest\032,.com.webank.ai.eggroll.a" +
      "pi.core.CallResponse\022e\n\010getNodes\022+.com.w" +
      "ebank.ai.eggroll.api.core.CallRequest\032,." +
      "com.webank.ai.eggroll.api.core.CallRespo" +
      "nse2\324\002\n\022ClusterMetaService\022i\n\014registerNo" +
      "de\022+.com.webank.ai.eggroll.api.core.Call" +
      "Request\032,.com.webank.ai.eggroll.api.core" +
      ".CallResponse\022k\n\016deregisterNode\022+.com.we" +
      "bank.ai.eggroll.api.core.CallRequest\032,.c" +
      "om.webank.ai.eggroll.api.core.CallRespon" +
      "se\022f\n\theartbeat\022+.com.webank.ai.eggroll." +
      "api.core.CallRequest\032,.com.webank.ai.egg" +
      "roll.api.core.CallResponse2\245\004\n\017TaskMetaS" +
      "ervice\022g\n\ncreateTask\022+.com.webank.ai.egg" +
      "roll.api.core.CallRequest\032,.com.webank.a" +
      "i.eggroll.api.core.CallResponse\022g\n\nupdat" +
      "eTask\022+.com.webank.ai.eggroll.api.core.C" +
      "allRequest\032,.com.webank.ai.eggroll.api.c" +
      "ore.CallResponse\022i\n\014createResult\022+.com.w" +
      "ebank.ai.eggroll.api.core.CallRequest\032,." +
      "com.webank.ai.eggroll.api.core.CallRespo" +
      "nse\022i\n\014updateResult\022+.com.webank.ai.eggr" +
      "oll.api.core.CallRequest\032,.com.webank.ai" +
      ".eggroll.api.core.CallResponse\022j\n\rgetRes" +
      "ultById\022+.com.webank.ai.eggroll.api.core" +
      ".CallRequest\032,.com.webank.ai.eggroll.api" +
      ".core.CallResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.webank.ai.eggroll.api.core.BasicMeta.getDescriptor(),
        });
    com.webank.ai.eggroll.api.core.BasicMeta.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
