data_guest: "breast_hetero_guest"
data_host: "breast_hetero_host"
idx: "id"
label_name: "y"
epochs: 20
init_param:
  fit_intercept: True
  method: "random_uniform"
  random_state: 42
learning_rate: 0.15
batch_size: null
early_stop: "diff"
task_cores: 4
timeout: 3600