log_directory:
console_display_log:
site_info:
  local_role: guest
  local_party_id:

standalone:
  job_dir:
  logger:
    level: "DEBUG"
    debug_mode: false
  device:
    type: "CPU"
  mlmd:
    type: pipeline
    metadata:
      db:
  computing:
    type: standalone
  federation_engine:
    type: standalone

fate_flow:
    ip: 127.0.0.1
    port: 9380
    version: v2
