data_guest: "examples/data/breast_hetero_guest.csv"
data_host: "examples/data/breast_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 33
alpha: 0.01
learning_rate: 0.15
optimizer: "sgd"
batch_size: 200
early_stop: "diff"
reveal_strategy: "respectively"