data_guest: "examples/data/breast_hetero_guest.csv"
data_host: "examples/data/breast_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 30
alpha: 0.01
learning_rate: 0.15
optimizer: "rmsprop"
batch_size: 5000
early_stop: "diff"