data_guest: "examples/data/give_credit_hetero_guest.csv"
data_host: "examples/data/give_credit_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 20
alpha: 10
learning_rate: 0.15
optimizer: "sgd"
batch_size: 5000
early_stop: "diff"
init_method: "zeros"
reveal_strategy: "respectively"