data_guest: "examples/data/vehicle_scale_hetero_guest.csv"
data_host: "examples/data/vehicle_scale_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 30
alpha: 0.00001
learning_rate: 0.45
optimizer: "adam"
batch_size: 20
early_stop: "diff"
init_method: "zeros"
reveal_strategy: "respectively"