# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data-io-param.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data-io-param.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x64\x61ta-io-param.proto\"\x1d\n\x0b\x44\x61taIOParam\x12\x0e\n\x06header\x18\x01 \x03(\tb\x06proto3')
)




_DATAIOPARAM = _descriptor.Descriptor(
  name='DataIOParam',
  full_name='DataIOParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='DataIOParam.header', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['DataIOParam'] = _DATAIOPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataIOParam = _reflection.GeneratedProtocolMessageType('DataIOParam', (_message.Message,), dict(
  DESCRIPTOR = _DATAIOPARAM,
  __module__ = 'data_io_param_pb2'
  # @@protoc_insertion_point(class_scope:DataIOParam)
  ))
_sym_db.RegisterMessage(DataIOParam)


# @@protoc_insertion_point(module_scope)
