# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ftl-model-meta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ftl-model-meta.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x66tl-model-meta.proto\"\x8e\x01\n\x0c\x46TLModelMeta\x12\x11\n\tinput_dim\x18\x01 \x01(\x05\x12\x12\n\nencode_dim\x18\x02 \x01(\x05\x12\x15\n\rlearning_rate\x18\x03 \x01(\x01\x12\x0b\n\x03\x65ps\x18\x04 \x01(\x01\x12\r\n\x05\x61lpha\x18\x05 \x01(\x01\x12\x12\n\nbatch_size\x18\x06 \x01(\x03\x12\x10\n\x08max_iter\x18\x07 \x01(\x03\x62\x06proto3')
)




_FTLMODELMETA = _descriptor.Descriptor(
  name='FTLModelMeta',
  full_name='FTLModelMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_dim', full_name='FTLModelMeta.input_dim', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encode_dim', full_name='FTLModelMeta.encode_dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='FTLModelMeta.learning_rate', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eps', full_name='FTLModelMeta.eps', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='FTLModelMeta.alpha', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='FTLModelMeta.batch_size', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_iter', full_name='FTLModelMeta.max_iter', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['FTLModelMeta'] = _FTLMODELMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FTLModelMeta = _reflection.GeneratedProtocolMessageType('FTLModelMeta', (_message.Message,), dict(
  DESCRIPTOR = _FTLMODELMETA,
  __module__ = 'ftl_model_meta_pb2'
  # @@protoc_insertion_point(class_scope:FTLModelMeta)
  ))
_sym_db.RegisterMessage(FTLModelMeta)


# @@protoc_insertion_point(module_scope)
