# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_param.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_param.proto',
  package='com.webank.ai.fate.common.mlmodel.buffer',
  syntax='proto3',
  serialized_options=_b('B\017ModelParamProto'),
  serialized_pb=_b('\n\x11model_param.proto\x12(com.webank.ai.fate.common.mlmodel.buffer\"\x1c\n\nModelParam\x12\x0e\n\x06weight\x18\x01 \x03(\x02\x42\x11\x42\x0fModelParamProtob\x06proto3')
)




_MODELPARAM = _descriptor.Descriptor(
  name='ModelParam',
  full_name='com.webank.ai.fate.common.mlmodel.buffer.ModelParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='com.webank.ai.fate.common.mlmodel.buffer.ModelParam.weight', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['ModelParam'] = _MODELPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelParam = _reflection.GeneratedProtocolMessageType('ModelParam', (_message.Message,), dict(
  DESCRIPTOR = _MODELPARAM,
  __module__ = 'model_param_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.common.mlmodel.buffer.ModelParam)
  ))
_sym_db.RegisterMessage(ModelParam)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
