# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_meta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_meta.proto',
  package='com.webank.ai.fate.core.mlmodel.buffer',
  syntax='proto3',
  serialized_options=_b('B\016ModelMetaProto'),
  serialized_pb=_b('\n\x10model_meta.proto\x12&com.webank.ai.fate.core.mlmodel.buffer\"\x7f\n\tModelMeta\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rfit_intercept\x18\x02 \x01(\x08\x12\x11\n\tcoef_size\x18\x03 \x01(\x05\x12\x16\n\x0e\x64\x61ta_transform\x18\x04 \x01(\x08\x12\"\n\x1a\x64\x61ta_transform_config_path\x18\x05 \x01(\tB\x10\x42\x0eModelMetaProtob\x06proto3')
)




_MODELMETA = _descriptor.Descriptor(
  name='ModelMeta',
  full_name='com.webank.ai.fate.core.mlmodel.buffer.ModelMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.webank.ai.fate.core.mlmodel.buffer.ModelMeta.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fit_intercept', full_name='com.webank.ai.fate.core.mlmodel.buffer.ModelMeta.fit_intercept', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coef_size', full_name='com.webank.ai.fate.core.mlmodel.buffer.ModelMeta.coef_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_transform', full_name='com.webank.ai.fate.core.mlmodel.buffer.ModelMeta.data_transform', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_transform_config_path', full_name='com.webank.ai.fate.core.mlmodel.buffer.ModelMeta.data_transform_config_path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['ModelMeta'] = _MODELMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelMeta = _reflection.GeneratedProtocolMessageType('ModelMeta', (_message.Message,), dict(
  DESCRIPTOR = _MODELMETA,
  __module__ = 'model_meta_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.core.mlmodel.buffer.ModelMeta)
  ))
_sym_db.RegisterMessage(ModelMeta)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
