# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import model_service_pb2 as model__service__pb2


class ModelServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.publishLoad = channel.unary_unary(
        '/com.webank.ai.fate.api.mlmodel.manager.ModelService/publishLoad',
        request_serializer=model__service__pb2.PublishRequest.SerializeToString,
        response_deserializer=model__service__pb2.PublishResponse.FromString,
        )
    self.publishOnline = channel.unary_unary(
        '/com.webank.ai.fate.api.mlmodel.manager.ModelService/publishOnline',
        request_serializer=model__service__pb2.PublishRequest.SerializeToString,
        response_deserializer=model__service__pb2.PublishResponse.FromString,
        )


class ModelServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def publishLoad(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def publishOnline(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'publishLoad': grpc.unary_unary_rpc_method_handler(
          servicer.publishLoad,
          request_deserializer=model__service__pb2.PublishRequest.FromString,
          response_serializer=model__service__pb2.PublishResponse.SerializeToString,
      ),
      'publishOnline': grpc.unary_unary_rpc_method_handler(
          servicer.publishOnline,
          request_deserializer=model__service__pb2.PublishRequest.FromString,
          response_serializer=model__service__pb2.PublishResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.webank.ai.fate.api.mlmodel.manager.ModelService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
