#
#  Copyright 2019 The FATE Authors. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_service.proto',
  package='com.webank.ai.fate.api.mlmodel.manager',
  syntax='proto3',
  serialized_options=_b('B\021ModelServiceProto'),
  serialized_pb=_b('\n\x13model_service.proto\x12&com.webank.ai.fate.api.mlmodel.manager\"\x18\n\x05Party\x12\x0f\n\x07partyId\x18\x01 \x03(\t\"*\n\tLocalInfo\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07partyId\x18\x02 \x01(\t\"1\n\tModelInfo\x12\x11\n\ttableName\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\"\xd9\x01\n\rRoleModelInfo\x12_\n\rroleModelInfo\x18\x01 \x03(\x0b\x32H.com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo.RoleModelInfoEntry\x1ag\n\x12RoleModelInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12@\n\x05value\x18\x02 \x01(\x0b\x32\x31.com.webank.ai.fate.api.mlmodel.manager.ModelInfo:\x02\x38\x01\"\xc8\x03\n\x0ePublishRequest\x12@\n\x05local\x18\x01 \x01(\x0b\x32\x31.com.webank.ai.fate.api.mlmodel.manager.LocalInfo\x12N\n\x04role\x18\x02 \x03(\x0b\x32@.com.webank.ai.fate.api.mlmodel.manager.PublishRequest.RoleEntry\x12P\n\x05model\x18\x03 \x03(\x0b\x32\x41.com.webank.ai.fate.api.mlmodel.manager.PublishRequest.ModelEntry\x12\x11\n\tserviceId\x18\x04 \x01(\t\x1aZ\n\tRoleEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12<\n\x05value\x18\x02 \x01(\x0b\x32-.com.webank.ai.fate.api.mlmodel.manager.Party:\x02\x38\x01\x1a\x63\n\nModelEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x44\n\x05value\x18\x02 \x01(\x0b\x32\x35.com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo:\x02\x38\x01\"S\n\x0fPublishResponse\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x32\x8e\x02\n\x0cModelService\x12~\n\x0bpublishLoad\x12\x36.com.webank.ai.fate.api.mlmodel.manager.PublishRequest\x1a\x37.com.webank.ai.fate.api.mlmodel.manager.PublishResponse\x12~\n\x0bpublishBind\x12\x36.com.webank.ai.fate.api.mlmodel.manager.PublishRequest\x1a\x37.com.webank.ai.fate.api.mlmodel.manager.PublishResponseB\x13\x42\x11ModelServiceProtob\x06proto3')
)




_PARTY = _descriptor.Descriptor(
  name='Party',
  full_name='com.webank.ai.fate.api.mlmodel.manager.Party',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partyId', full_name='com.webank.ai.fate.api.mlmodel.manager.Party.partyId', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=87,
)


_LOCALINFO = _descriptor.Descriptor(
  name='LocalInfo',
  full_name='com.webank.ai.fate.api.mlmodel.manager.LocalInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='com.webank.ai.fate.api.mlmodel.manager.LocalInfo.role', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partyId', full_name='com.webank.ai.fate.api.mlmodel.manager.LocalInfo.partyId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=131,
)


_MODELINFO = _descriptor.Descriptor(
  name='ModelInfo',
  full_name='com.webank.ai.fate.api.mlmodel.manager.ModelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableName', full_name='com.webank.ai.fate.api.mlmodel.manager.ModelInfo.tableName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='com.webank.ai.fate.api.mlmodel.manager.ModelInfo.namespace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=182,
)


_ROLEMODELINFO_ROLEMODELINFOENTRY = _descriptor.Descriptor(
  name='RoleModelInfoEntry',
  full_name='com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo.RoleModelInfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo.RoleModelInfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo.RoleModelInfoEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=402,
)

_ROLEMODELINFO = _descriptor.Descriptor(
  name='RoleModelInfo',
  full_name='com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roleModelInfo', full_name='com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo.roleModelInfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ROLEMODELINFO_ROLEMODELINFOENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=402,
)


_PUBLISHREQUEST_ROLEENTRY = _descriptor.Descriptor(
  name='RoleEntry',
  full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest.RoleEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest.RoleEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest.RoleEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=670,
  serialized_end=760,
)

_PUBLISHREQUEST_MODELENTRY = _descriptor.Descriptor(
  name='ModelEntry',
  full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest.ModelEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest.ModelEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest.ModelEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=762,
  serialized_end=861,
)

_PUBLISHREQUEST = _descriptor.Descriptor(
  name='PublishRequest',
  full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest.local', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest.role', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest.model', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceId', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishRequest.serviceId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PUBLISHREQUEST_ROLEENTRY, _PUBLISHREQUEST_MODELENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=861,
)


_PUBLISHRESPONSE = _descriptor.Descriptor(
  name='PublishResponse',
  full_name='com.webank.ai.fate.api.mlmodel.manager.PublishResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishResponse.statusCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishResponse.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='com.webank.ai.fate.api.mlmodel.manager.PublishResponse.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=863,
  serialized_end=946,
)

_ROLEMODELINFO_ROLEMODELINFOENTRY.fields_by_name['value'].message_type = _MODELINFO
_ROLEMODELINFO_ROLEMODELINFOENTRY.containing_type = _ROLEMODELINFO
_ROLEMODELINFO.fields_by_name['roleModelInfo'].message_type = _ROLEMODELINFO_ROLEMODELINFOENTRY
_PUBLISHREQUEST_ROLEENTRY.fields_by_name['value'].message_type = _PARTY
_PUBLISHREQUEST_ROLEENTRY.containing_type = _PUBLISHREQUEST
_PUBLISHREQUEST_MODELENTRY.fields_by_name['value'].message_type = _ROLEMODELINFO
_PUBLISHREQUEST_MODELENTRY.containing_type = _PUBLISHREQUEST
_PUBLISHREQUEST.fields_by_name['local'].message_type = _LOCALINFO
_PUBLISHREQUEST.fields_by_name['role'].message_type = _PUBLISHREQUEST_ROLEENTRY
_PUBLISHREQUEST.fields_by_name['model'].message_type = _PUBLISHREQUEST_MODELENTRY
DESCRIPTOR.message_types_by_name['Party'] = _PARTY
DESCRIPTOR.message_types_by_name['LocalInfo'] = _LOCALINFO
DESCRIPTOR.message_types_by_name['ModelInfo'] = _MODELINFO
DESCRIPTOR.message_types_by_name['RoleModelInfo'] = _ROLEMODELINFO
DESCRIPTOR.message_types_by_name['PublishRequest'] = _PUBLISHREQUEST
DESCRIPTOR.message_types_by_name['PublishResponse'] = _PUBLISHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Party = _reflection.GeneratedProtocolMessageType('Party', (_message.Message,), dict(
  DESCRIPTOR = _PARTY,
  __module__ = 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.mlmodel.manager.Party)
  ))
_sym_db.RegisterMessage(Party)

LocalInfo = _reflection.GeneratedProtocolMessageType('LocalInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOCALINFO,
  __module__ = 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.mlmodel.manager.LocalInfo)
  ))
_sym_db.RegisterMessage(LocalInfo)

ModelInfo = _reflection.GeneratedProtocolMessageType('ModelInfo', (_message.Message,), dict(
  DESCRIPTOR = _MODELINFO,
  __module__ = 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.mlmodel.manager.ModelInfo)
  ))
_sym_db.RegisterMessage(ModelInfo)

RoleModelInfo = _reflection.GeneratedProtocolMessageType('RoleModelInfo', (_message.Message,), dict(

  RoleModelInfoEntry = _reflection.GeneratedProtocolMessageType('RoleModelInfoEntry', (_message.Message,), dict(
    DESCRIPTOR = _ROLEMODELINFO_ROLEMODELINFOENTRY,
    __module__ = 'model_service_pb2'
    # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo.RoleModelInfoEntry)
    ))
  ,
  DESCRIPTOR = _ROLEMODELINFO,
  __module__ = 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo)
  ))
_sym_db.RegisterMessage(RoleModelInfo)
_sym_db.RegisterMessage(RoleModelInfo.RoleModelInfoEntry)

PublishRequest = _reflection.GeneratedProtocolMessageType('PublishRequest', (_message.Message,), dict(

  RoleEntry = _reflection.GeneratedProtocolMessageType('RoleEntry', (_message.Message,), dict(
    DESCRIPTOR = _PUBLISHREQUEST_ROLEENTRY,
    __module__ = 'model_service_pb2'
    # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.mlmodel.manager.PublishRequest.RoleEntry)
    ))
  ,

  ModelEntry = _reflection.GeneratedProtocolMessageType('ModelEntry', (_message.Message,), dict(
    DESCRIPTOR = _PUBLISHREQUEST_MODELENTRY,
    __module__ = 'model_service_pb2'
    # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.mlmodel.manager.PublishRequest.ModelEntry)
    ))
  ,
  DESCRIPTOR = _PUBLISHREQUEST,
  __module__ = 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.mlmodel.manager.PublishRequest)
  ))
_sym_db.RegisterMessage(PublishRequest)
_sym_db.RegisterMessage(PublishRequest.RoleEntry)
_sym_db.RegisterMessage(PublishRequest.ModelEntry)

PublishResponse = _reflection.GeneratedProtocolMessageType('PublishResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUBLISHRESPONSE,
  __module__ = 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.mlmodel.manager.PublishResponse)
  ))
_sym_db.RegisterMessage(PublishResponse)


DESCRIPTOR._options = None
_ROLEMODELINFO_ROLEMODELINFOENTRY._options = None
_PUBLISHREQUEST_ROLEENTRY._options = None
_PUBLISHREQUEST_MODELENTRY._options = None

_MODELSERVICE = _descriptor.ServiceDescriptor(
  name='ModelService',
  full_name='com.webank.ai.fate.api.mlmodel.manager.ModelService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=949,
  serialized_end=1219,
  methods=[
  _descriptor.MethodDescriptor(
    name='publishLoad',
    full_name='com.webank.ai.fate.api.mlmodel.manager.ModelService.publishLoad',
    index=0,
    containing_service=None,
    input_type=_PUBLISHREQUEST,
    output_type=_PUBLISHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='publishBind',
    full_name='com.webank.ai.fate.api.mlmodel.manager.ModelService.publishBind',
    index=1,
    containing_service=None,
    input_type=_PUBLISHREQUEST,
    output_type=_PUBLISHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELSERVICE)

DESCRIPTOR.services_by_name['ModelService'] = _MODELSERVICE

# @@protoc_insertion_point(module_scope)
