# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fate-data-structure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66\x61te-data-structure.proto\x12\x1b\x63om.webank.ai.fate.api.core\"&\n\x08RawEntry\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"@\n\x06RawMap\x12\x36\n\x07\x65ntries\x18\x01 \x03(\x0b\x32%.com.webank.ai.fate.api.core.RawEntry\"n\n\x04\x44ict\x12\x39\n\x04\x64ict\x18\x01 \x03(\x0b\x32+.com.webank.ai.fate.api.core.Dict.DictEntry\x1a+\n\tDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x42\x0f\x42\rDataStructureb\x06proto3')



_RAWENTRY = DESCRIPTOR.message_types_by_name['RawEntry']
_RAWMAP = DESCRIPTOR.message_types_by_name['RawMap']
_DICT = DESCRIPTOR.message_types_by_name['Dict']
_DICT_DICTENTRY = _DICT.nested_types_by_name['DictEntry']
RawEntry = _reflection.GeneratedProtocolMessageType('RawEntry', (_message.Message,), {
  'DESCRIPTOR' : _RAWENTRY,
  '__module__' : 'fate_data_structure_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.core.RawEntry)
  })
_sym_db.RegisterMessage(RawEntry)

RawMap = _reflection.GeneratedProtocolMessageType('RawMap', (_message.Message,), {
  'DESCRIPTOR' : _RAWMAP,
  '__module__' : 'fate_data_structure_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.core.RawMap)
  })
_sym_db.RegisterMessage(RawMap)

Dict = _reflection.GeneratedProtocolMessageType('Dict', (_message.Message,), {

  'DictEntry' : _reflection.GeneratedProtocolMessageType('DictEntry', (_message.Message,), {
    'DESCRIPTOR' : _DICT_DICTENTRY,
    '__module__' : 'fate_data_structure_pb2'
    # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.core.Dict.DictEntry)
    })
  ,
  'DESCRIPTOR' : _DICT,
  '__module__' : 'fate_data_structure_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.core.Dict)
  })
_sym_db.RegisterMessage(Dict)
_sym_db.RegisterMessage(Dict.DictEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\rDataStructure'
  _DICT_DICTENTRY._options = None
  _DICT_DICTENTRY._serialized_options = b'8\001'
  _RAWENTRY._serialized_start=58
  _RAWENTRY._serialized_end=96
  _RAWMAP._serialized_start=98
  _RAWMAP._serialized_end=162
  _DICT._serialized_start=164
  _DICT._serialized_end=274
  _DICT_DICTENTRY._serialized_start=231
  _DICT_DICTENTRY._serialized_end=274
# @@protoc_insertion_point(module_scope)
