image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

vscode:
  extensions:
    - ms-python.python

tasks:
  - name: vscode settings
    init: |
      mkdir -p "$PWD/.vscode";
      cat << 'EOF' > "$PWD/.vscode/settings.json"
      { 
        "python.envFile": "${workspaceFolder}/.vscode/.env",
        "python.defaultInterpreterPath": "/venv/py36/bin/python",
        "python.pythonPath": "/venv/py36/bin/python",
        "python.autoComplete.extraPaths": ["python", "python/fate_client", "python/fate_test", "fateflow/python", "eggroll/python"],
        "git.alwaysSignOff": true
      }
      EOF
      cat << 'EOF' > "$PWD/.vscode/.env"
      PYTHONPATH=/workspace/FATE/python:/workspace/FATE/fateflow/python:${PYTHONPATH}
      EOF
    command: exit
  
  - name: fate
    init: |
      unset PIP_USER && unset PYTHONUSERBASE
      cat << 'EOF' >> "$PWD/.git/info/exclude"
      /bin/init_env.sh
      EOF
      sed -i 's#export PYTHONPATH=#export PYTHONPATH=/workspace/FATE/python:/workspace/FATE/fateflow/python:/workspace/FATE/eggroll/python#' bin/init_env.sh
      sed -i 's#venv=.*#venv=/venv/py36#' bin/init_env.sh

    command: | 
      git update-index --assume-unchanged bin/init_env.sh \
      && source /workspace/FATE/bin/init_env.sh \
      && bash /workspace/FATE/fateflow/bin/service.sh start \
      && nohup java -Dspring.config.location=/fateboard/resources/application.properties \
      -DFATE_DEPLOY_PREFIX=/workspace/FATE/fateflow/logs/ \
      -Dssh_config_file=/fateboard/resources/ \
      -Xmx2048m -Xms2048m -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:gc.log -XX:+HeapDumpOnOutOfMemoryError \
      -jar /fateboard/fateboard.jar >/dev/null 2>&1 &
      echo done


ports:
  - port: 9380
    onOpen: ignore
  - port: 9360
    onOpen: ignore
  - port: 8080
    onOpen: open-browser