version: 2

mkdocs:
  # configuration: .readthedocs.mkdocs.yml
  fail_on_warning: false

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
python:
  install:
  - requirements: doc/mkdocs/requirements.txt
