[tool.autoflake]
check = false
exclude = ["examples/*", "python/fate_test/*", "python/fate_client/*", "doc/*", "deploy/*", "c/*", "rust/*"]

[tool.isort]
profile = "black"
skip_glob = ["examples/*", "python/fate_test/*", "python/fate_client/*", "doc/*", "deploy/*", "c/*", "rust/*"]

[tool.black]
target-version = ['py38']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
force-exclude = '''
(
  .*_pb2.py |
  ^/examples/ |
  ^/python/fate_test/ |
  ^/python/fate_client/ |
  ^/rust/ |
  ^/c/ |
  ^/doc/ |
  ^/deploy/
)
'''

[tool.pyright]
include = ["python"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/typestubs"
]
defineConstant = { DEBUG = true }
reportMissingImports = true
reportMissingTypeStubs = false
executionEnvironments = [
  { root = "python" },
]
