[tool.autoflake]
check = false
exclude = ["examples/*", "python/fate_test/*", "python/fate_client/*", "doc/*", "deploy/*", "c/*", "rust/*"]

[tool.isort]
profile = "black"
skip_glob = ["examples/*", "python/fate_test/*", "python/fate_client/*", "doc/*", "deploy/*", "c/*", "rust/*", "*_pb2.py", "*_pb2_grpc.py"]

[tool.black]
line-length = 119
target-version = ['py38']
include = '\.pyi?$'
force-exclude = '''
/(
  .*_pb2.py |
  .*_pb2_grpc.py |
  ^/examples/ |
  ^/python/fate_client/ |
  ^/rust/ |
  ^/c/ |
  ^/doc/ |
  ^/deploy/
)\
'''

[tool.pyright]
include = ["python"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/typestubs"
]
defineConstant = { DEBUG = true }
reportMissingImports = true
reportMissingTypeStubs = false
executionEnvironments = [
  { root = "python" },
]
