execution_id: xxx
component: hetero_lr
role: guest
stage: predict
inputs:
  parameters:
    learning_rate: 0.2
    max_iter: 100
  artifacts:
    test_data:
      - name: test_data1
        uri: file:///tmp/test_data1
        metadata:
          format: csv
      - name: test_data2
        uri: file:///tmp/test_data2
        metadata:
          format: csv
    input_model:
      name: input_model
      uri: file:///tmp/trained_model
outputs:
  artifacts:
    test_output_data:
      name: train_output_data
      uri: file:///tmp/train_data_forward
      metadata:
        format: csv
env:
  mlmd:
    type: pipeline
    metadata:
      state_path: /Users/sage/fate_tmp/state
      terminate_state_path: /Users/sage/fate_tmp/terminate_state
  logger:
    type: pipeline
    metadata:
      basepath: /Users/sage/fate_tmp/logs
      level: DEBUG
      debug_mode: true
  device: CPU
  distributed_computing_backend:
    engine: standalone
    computing_id: xxxx
  federation_backend:
    engine: standalone
    federation_id: xxx
    parties:
      local:
        role: guest
        partyid: "9999"
      parties:
        - role: host
          partyid: "10000"
        - role: arbiter
          partyid: "10001"
