log_directory:
console_display_log:

fate_standalone:
    job_directory:
    output_data_dir:
    output_model_dir:
    output_metric_dir:
    output_status_dir:
    computing_engine: "standalone"
    federation_engine: "standalone"
    device: "CPU"

fate_flow:
    ip:
    port:
    backend:
