log_directory:
console_display_log:

standalone:
  sqlite_db:
  job_directory:
  output_data_dir:
  output_model_dir:
  output_metric_dir:
  computing_engine: "standalone"
  federation_engine: "standalone"
  logger:
    level: "DEBUG"
    debug_mode: true
  engine:
    device: "CPU"

fate_flow:
    ip:
    port:
    backend: