data_guest: "examples/data/default_credit_homo_guest.csv"
data_host: "examples/data/default_credit_homo_host_1.csv"
data_test: "examples/data/default_credit_homo_test.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 30
alpha: 0.01
batch_size: 320
learning_rate: 0.15
optimizer: "rmsprop"

