data_guest: "examples/data/vehicle_scale_homo_guest.csv"
data_host: "examples/data/vehicle_scale_homo_host.csv"
data_test: "examples/data/vehicle_scale_homo_test.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 30
alpha: 0.01
batch_size: 32
learning_rate: 0.15
optimizer: "rmsprop"
