data_guest: "examples/data/student_hetero_guest.csv"
data_host: "examples/data/student_hetero_host.csv"
idx: "id"
label_name: "y"
max_depth: 3
max_bin: 32
learning_rate: 0.3
n_estimators: 50
objective: "reg:squarederror"
