data_guest: "examples/data/epsilon_5k_hetero_guest.csv"
data_host: "examples/data/epsilon_5k_hetero_host.csv"
idx: "id"
label_name: "y"
learning_rate: 0.03
tol: 0.01
batch_size: -1
metrics: ["AUC"]
epochs: 100
guest_table_name: "epsilon_5k_hetero_guest"
host_table_name: "epsilon_5k_hetero_host"
eval_type: "binary"
guest_input_shape: 20
host_input_shape: 80
