data_guest: "examples/data/vehicle_scale_homo_guest.csv"
data_host: "examples/data/vehicle_scale_homo_host.csv"
data_test: "examples/data/vehicle_scale_homo_test.csv"
idx: "id"
label_name: "y"
in_feat: 18
out_feat: 8
lr: 0.1
batch_size: 32
epochs: 100
class_num: 4