data_guest: "examples/data/default_credit_homo_guest.csv"
data_host: "examples/data/default_credit_homo_host_1.csv"
data_test: "examples/data/default_credit_homo_test.csv"
idx: "id"
label_name: "y"
in_feat: 23
out_feat: 10
lr: 0.01
batch_size: 32
epochs: 50