data_guest_train: "vehicle_scale_homo_guest"
data_guest_val: "vehicle_scale_homo_guest"
data_host_train: "vehicle_scale_homo_host"
data_host_val: "vehicle_scale_homo_host"
eval_type: "multi"
task_type: "classification"
loss_func: "cross_entropy"
tree_depth: 3
tree_num: 10
learning_rate: 0.1