[package]
name = "paillier_tensor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
rayon = { workspace = true }
numpy = { workspace = true }
ndarray = { workspace = true }
math = { path = "../math" }
fixedpoint = { path = "../fixedpoint" }
