# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pcp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pcp.proto',
  package='org.ppc.ptp',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tpcp.proto\x12\x0borg.ppc.ptp\"\x81\x01\n\x07Inbound\x12\x34\n\x08metadata\x18\x01 \x03(\x0b\x32\".org.ppc.ptp.Inbound.MetadataEntry\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa2\x01\n\x08Outbound\x12\x35\n\x08metadata\x18\x01 \x03(\x0b\x32#.org.ppc.ptp.Outbound.MetadataEntry\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x9a\x01\n\x06Header\x12\x0b\n\x07Version\x10\x00\x12\x14\n\x10TechProviderCode\x10\x01\x12\x0b\n\x07TraceID\x10\x04\x12\t\n\x05Token\x10\x05\x12\x10\n\x0cSourceNodeID\x10\x06\x12\x10\n\x0cTargetNodeID\x10\x07\x12\x10\n\x0cSourceInstID\x10\x08\x12\x10\n\x0cTargetInstID\x10\t\x12\r\n\tSessionID\x10\n*\xa3\x01\n\x08Metadata\x12\x10\n\x0cMessageTopic\x10\x00\x12\x0f\n\x0bMessageCode\x10\x01\x12\x17\n\x13SourceComponentName\x10\x02\x12\x17\n\x13TargetComponentName\x10\x03\x12\x10\n\x0cTargetMethod\x10\x04\x12\x11\n\rMessageOffSet\x10\x05\x12\x0e\n\nInstanceId\x10\x06\x12\r\n\tTimestamp\x10\x07\x32\x8e\x01\n\x17PrivateTransferProtocol\x12<\n\ttransport\x12\x14.org.ppc.ptp.Inbound\x1a\x15.org.ppc.ptp.Outbound(\x01\x30\x01\x12\x35\n\x06invoke\x12\x14.org.ppc.ptp.Inbound\x1a\x15.org.ppc.ptp.Outboundb\x06proto3')
)

_HEADER = _descriptor.EnumDescriptor(
  name='Header',
  full_name='org.ppc.ptp.Header',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Version', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TechProviderCode', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TraceID', index=2, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Token', index=3, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SourceNodeID', index=4, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TargetNodeID', index=5, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SourceInstID', index=6, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TargetInstID', index=7, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SessionID', index=8, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=324,
  serialized_end=478,
)
_sym_db.RegisterEnumDescriptor(_HEADER)

Header = enum_type_wrapper.EnumTypeWrapper(_HEADER)
_METADATA = _descriptor.EnumDescriptor(
  name='Metadata',
  full_name='org.ppc.ptp.Metadata',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MessageTopic', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MessageCode', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SourceComponentName', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TargetComponentName', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TargetMethod', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MessageOffSet', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InstanceId', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Timestamp', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=481,
  serialized_end=644,
)
_sym_db.RegisterEnumDescriptor(_METADATA)

Metadata = enum_type_wrapper.EnumTypeWrapper(_METADATA)
Version = 0
TechProviderCode = 1
TraceID = 4
Token = 5
SourceNodeID = 6
TargetNodeID = 7
SourceInstID = 8
TargetInstID = 9
SessionID = 10
MessageTopic = 0
MessageCode = 1
SourceComponentName = 2
TargetComponentName = 3
TargetMethod = 4
MessageOffSet = 5
InstanceId = 6
Timestamp = 7



_INBOUND_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='org.ppc.ptp.Inbound.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.ppc.ptp.Inbound.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.ppc.ptp.Inbound.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=156,
)

_INBOUND = _descriptor.Descriptor(
  name='Inbound',
  full_name='org.ppc.ptp.Inbound',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='org.ppc.ptp.Inbound.metadata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='org.ppc.ptp.Inbound.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INBOUND_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=156,
)


_OUTBOUND_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='org.ppc.ptp.Outbound.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.ppc.ptp.Outbound.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.ppc.ptp.Outbound.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=156,
)

_OUTBOUND = _descriptor.Descriptor(
  name='Outbound',
  full_name='org.ppc.ptp.Outbound',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='org.ppc.ptp.Outbound.metadata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='org.ppc.ptp.Outbound.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='org.ppc.ptp.Outbound.code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='org.ppc.ptp.Outbound.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OUTBOUND_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=321,
)

_INBOUND_METADATAENTRY.containing_type = _INBOUND
_INBOUND.fields_by_name['metadata'].message_type = _INBOUND_METADATAENTRY
_OUTBOUND_METADATAENTRY.containing_type = _OUTBOUND
_OUTBOUND.fields_by_name['metadata'].message_type = _OUTBOUND_METADATAENTRY
DESCRIPTOR.message_types_by_name['Inbound'] = _INBOUND
DESCRIPTOR.message_types_by_name['Outbound'] = _OUTBOUND
DESCRIPTOR.enum_types_by_name['Header'] = _HEADER
DESCRIPTOR.enum_types_by_name['Metadata'] = _METADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Inbound = _reflection.GeneratedProtocolMessageType('Inbound', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _INBOUND_METADATAENTRY,
    '__module__' : 'pcp_pb2'
    # @@protoc_insertion_point(class_scope:org.ppc.ptp.Inbound.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _INBOUND,
  '__module__' : 'pcp_pb2'
  # @@protoc_insertion_point(class_scope:org.ppc.ptp.Inbound)
  })
_sym_db.RegisterMessage(Inbound)
_sym_db.RegisterMessage(Inbound.MetadataEntry)

Outbound = _reflection.GeneratedProtocolMessageType('Outbound', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _OUTBOUND_METADATAENTRY,
    '__module__' : 'pcp_pb2'
    # @@protoc_insertion_point(class_scope:org.ppc.ptp.Outbound.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _OUTBOUND,
  '__module__' : 'pcp_pb2'
  # @@protoc_insertion_point(class_scope:org.ppc.ptp.Outbound)
  })
_sym_db.RegisterMessage(Outbound)
_sym_db.RegisterMessage(Outbound.MetadataEntry)


_INBOUND_METADATAENTRY._options = None
_OUTBOUND_METADATAENTRY._options = None

_PRIVATETRANSFERPROTOCOL = _descriptor.ServiceDescriptor(
  name='PrivateTransferProtocol',
  full_name='org.ppc.ptp.PrivateTransferProtocol',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=647,
  serialized_end=789,
  methods=[
  _descriptor.MethodDescriptor(
    name='transport',
    full_name='org.ppc.ptp.PrivateTransferProtocol.transport',
    index=0,
    containing_service=None,
    input_type=_INBOUND,
    output_type=_OUTBOUND,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='invoke',
    full_name='org.ppc.ptp.PrivateTransferProtocol.invoke',
    index=1,
    containing_service=None,
    input_type=_INBOUND,
    output_type=_OUTBOUND,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRIVATETRANSFERPROTOCOL)

DESCRIPTOR.services_by_name['PrivateTransferProtocol'] = _PRIVATETRANSFERPROTOCOL

# @@protoc_insertion_point(module_scope)
