party_id: "9999"
use_registry: false
# DEBUG 10/INFO 20
log_level: 20
encrypt:
  key_0:
    module: fate_flow.hub.encrypt.password_encrypt#pwdecrypt
    # base on: fate_flow/conf/
    private_path: private_key.pem
fateflow:
  host: 192.167.0.100
  http_port: 9380
  grpc_port: 9360
  proxy_name: osx
#  nginx:
#    host:
#    http_port:
#    grpc_port:
database:
  engine: mysql
  # encrypt passwd key
  decrypt_key:
  mysql:
    name: <db_name>
    user: <db_user>
    passwd: <db_passwd>
    host: <db_host>
    port: 3306
    max_connections: 100
    stale_timeout: 30
  sqlite:
    # default fate_flow/runtime/system_settings: SQLITE_PATH
    # /xxx/xxx.sqlite
    path:
default_engines:
  computing: eggroll
  federation: osx
  storage: eggroll
default_provider:
  name: fate
  # version default: fateflow.env
  version:
  device: local
computing:
  standalone:
    cores: 32
  eggroll:
    cores: 32
    nodes: 1
    # cluster manager host and port
    host: clustermanager
    port: 4670
  spark:
    # default use SPARK_HOME environment variable
    home: /data/projects/spark-3.1.3-bin-hadoop3.2/
    cores: 32
federation:
  osx:
    host: osx
    port: 9370
    # stream or queue
    mode: stream
  pulsar:
    host: pulsar
    port: 6650
    mng_port: 8080
    cluster: standalone
    tenant: fl-tenant
    topic_ttl: 30
    # default conf/pulsar_route_table.yaml
    route_table: conf/pulsar_route_table.yaml
    # mode: replication / client, default: replication
    mode: replication
    max_message_size: 1048576
  nginx:
    host: nginx
    http_port: 9300
    grpc_port: 9310
    # http or grpc
    protocol: http
  rabbitmq:
    host: rabbitmq
    mng_port: 15672
    port: 5672
    user: fate
    password: fate
    # default conf/rabbitmq_route_table.yaml
    route_table: conf/pulsar_route_table.yaml
    # mode: replication / client, default: replication
    mode: replication
storage:
  hdfs:
    name_node: hdfs://namenode:9000
hook_module:
  client_authentication: fate_flow.hook.flow.client_authentication
  site_authentication: fate_flow.hook.flow.site_authentication
  permission: fate_flow.hook.flow.permission
authentication:
  client: false
  site: false
  permission: false
model_store:
  engine: file
  # encrypt passwd key
  decrypt_key:
  file:
    # default fate_flow/runtime/system_settings: MODEL_STORE_PATH
    path:
  mysql:
    name: fate_flow
    user: fate
    passwd: fate
    host: 127.0.0.1
    port: 3306
    max_connections: 100
    stale_timeout: 30
  tencent_cos:
    Region:
    SecretId:
    SecretKey:
    Bucket:
zookeeper:
  hosts:
    - 127.0.0.1:2181
  use_acl: true
  user: fate
  password: fate
