data_guest: "examples/data/motor_hetero_guest.csv"
data_host: "examples/data/motor_hetero_host.csv"
idx: "idx"
label_name: "motor_speed"
penalty: "L2"
max_iter: 6
optimizer: "sgd"
batch_size: 100
learning_rate: 0.13
alpha: 0.01
tol: 1e-4
init_param:
  init_method: "zeros"
