// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eggroll/command.proto

package com.webank.eggroll.core.command;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommandRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.webank.eggroll.core.command.CommandRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string uri = 2;</code>
     * @return The uri.
     */
    java.lang.String getUri();
    /**
     * <code>string uri = 2;</code>
     * @return The bytes for uri.
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <code>repeated bytes args = 3;</code>
     * @return A list containing the args.
     */
    java.util.List<com.google.protobuf.ByteString> getArgsList();
    /**
     * <code>repeated bytes args = 3;</code>
     * @return The count of args.
     */
    int getArgsCount();
    /**
     * <code>repeated bytes args = 3;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    com.google.protobuf.ByteString getArgs(int index);

    /**
     * <pre>
     * reserved for scala / python etc.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
     */
    int getKwargsCount();
    /**
     * <pre>
     * reserved for scala / python etc.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
     */
    boolean containsKwargs(
        java.lang.String key);
    /**
     * Use {@link #getKwargsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getKwargs();
    /**
     * <pre>
     * reserved for scala / python etc.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getKwargsMap();
    /**
     * <pre>
     * reserved for scala / python etc.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
     */
    /* nullable */
com.google.protobuf.ByteString getKwargsOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.ByteString defaultValue);
    /**
     * <pre>
     * reserved for scala / python etc.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
     */
    com.google.protobuf.ByteString getKwargsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.webank.eggroll.core.command.CommandRequest}
   */
  public static final class CommandRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.webank.eggroll.core.command.CommandRequest)
      CommandRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommandRequest.newBuilder() to construct.
    private CommandRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandRequest() {
      id_ = "";
      uri_ = "";
      args_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CommandRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetKwargs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.webank.eggroll.core.command.Command.CommandRequest.class, com.webank.eggroll.core.command.Command.CommandRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URI_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uri_ = "";
    /**
     * <code>string uri = 2;</code>
     * @return The uri.
     */
    @java.lang.Override
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <code>string uri = 2;</code>
     * @return The bytes for uri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.ByteString> args_;
    /**
     * <code>repeated bytes args = 3;</code>
     * @return A list containing the args.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getArgsList() {
      return args_;
    }
    /**
     * <code>repeated bytes args = 3;</code>
     * @return The count of args.
     */
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <code>repeated bytes args = 3;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    public com.google.protobuf.ByteString getArgs(int index) {
      return args_.get(index);
    }

    public static final int KWARGS_FIELD_NUMBER = 4;
    private static final class KwargsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.ByteString> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                  com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandRequest_KwargsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.BYTES,
                  com.google.protobuf.ByteString.EMPTY);
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> kwargs_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetKwargs() {
      if (kwargs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            KwargsDefaultEntryHolder.defaultEntry);
      }
      return kwargs_;
    }
    public int getKwargsCount() {
      return internalGetKwargs().getMap().size();
    }
    /**
     * <pre>
     * reserved for scala / python etc.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
     */
    @java.lang.Override
    public boolean containsKwargs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetKwargs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getKwargsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getKwargs() {
      return getKwargsMap();
    }
    /**
     * <pre>
     * reserved for scala / python etc.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getKwargsMap() {
      return internalGetKwargs().getMap();
    }
    /**
     * <pre>
     * reserved for scala / python etc.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.ByteString getKwargsOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetKwargs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * reserved for scala / python etc.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKwargsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetKwargs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uri_);
      }
      for (int i = 0; i < args_.size(); i++) {
        output.writeBytes(3, args_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetKwargs(),
          KwargsDefaultEntryHolder.defaultEntry,
          4);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uri_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < args_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(args_.get(i));
        }
        size += dataSize;
        size += 1 * getArgsList().size();
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
           : internalGetKwargs().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
        kwargs__ = KwargsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, kwargs__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.webank.eggroll.core.command.Command.CommandRequest)) {
        return super.equals(obj);
      }
      com.webank.eggroll.core.command.Command.CommandRequest other = (com.webank.eggroll.core.command.Command.CommandRequest) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getUri()
          .equals(other.getUri())) return false;
      if (!getArgsList()
          .equals(other.getArgsList())) return false;
      if (!internalGetKwargs().equals(
          other.internalGetKwargs())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      if (getArgsCount() > 0) {
        hash = (37 * hash) + ARGS_FIELD_NUMBER;
        hash = (53 * hash) + getArgsList().hashCode();
      }
      if (!internalGetKwargs().getMap().isEmpty()) {
        hash = (37 * hash) + KWARGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetKwargs().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.webank.eggroll.core.command.Command.CommandRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.webank.eggroll.core.command.Command.CommandRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.webank.eggroll.core.command.Command.CommandRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.webank.eggroll.core.command.CommandRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.webank.eggroll.core.command.CommandRequest)
        com.webank.eggroll.core.command.Command.CommandRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetKwargs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableKwargs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.webank.eggroll.core.command.Command.CommandRequest.class, com.webank.eggroll.core.command.Command.CommandRequest.Builder.class);
      }

      // Construct using com.webank.eggroll.core.command.Command.CommandRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        uri_ = "";
        args_ = java.util.Collections.emptyList();
        internalGetMutableKwargs().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandRequest_descriptor;
      }

      @java.lang.Override
      public com.webank.eggroll.core.command.Command.CommandRequest getDefaultInstanceForType() {
        return com.webank.eggroll.core.command.Command.CommandRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.webank.eggroll.core.command.Command.CommandRequest build() {
        com.webank.eggroll.core.command.Command.CommandRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.webank.eggroll.core.command.Command.CommandRequest buildPartial() {
        com.webank.eggroll.core.command.Command.CommandRequest result = new com.webank.eggroll.core.command.Command.CommandRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.webank.eggroll.core.command.Command.CommandRequest result) {
        if (((bitField0_ & 0x00000004) != 0)) {
          args_ = java.util.Collections.unmodifiableList(args_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.args_ = args_;
      }

      private void buildPartial0(com.webank.eggroll.core.command.Command.CommandRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.uri_ = uri_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.kwargs_ = internalGetKwargs();
          result.kwargs_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.webank.eggroll.core.command.Command.CommandRequest) {
          return mergeFrom((com.webank.eggroll.core.command.Command.CommandRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.webank.eggroll.core.command.Command.CommandRequest other) {
        if (other == com.webank.eggroll.core.command.Command.CommandRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.args_.isEmpty()) {
          if (args_.isEmpty()) {
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureArgsIsMutable();
            args_.addAll(other.args_);
          }
          onChanged();
        }
        internalGetMutableKwargs().mergeFrom(
            other.internalGetKwargs());
        bitField0_ |= 0x00000008;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                uri_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureArgsIsMutable();
                args_.add(v);
                break;
              } // case 26
              case 34: {
                com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
                kwargs__ = input.readMessage(
                    KwargsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableKwargs().getMutableMap().put(
                    kwargs__.getKey(), kwargs__.getValue());
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <code>string uri = 2;</code>
       * @return The uri.
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uri = 2;</code>
       * @return The bytes for uri.
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uri = 2;</code>
       * @param value The uri to set.
       * @return This builder for chaining.
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uri_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUri() {
        uri_ = getDefaultInstance().getUri();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 2;</code>
       * @param value The bytes for uri to set.
       * @return This builder for chaining.
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uri_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> args_ = java.util.Collections.emptyList();
      private void ensureArgsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          args_ = new java.util.ArrayList<com.google.protobuf.ByteString>(args_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <code>repeated bytes args = 3;</code>
       * @return A list containing the args.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getArgsList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(args_) : args_;
      }
      /**
       * <code>repeated bytes args = 3;</code>
       * @return The count of args.
       */
      public int getArgsCount() {
        return args_.size();
      }
      /**
       * <code>repeated bytes args = 3;</code>
       * @param index The index of the element to return.
       * @return The args at the given index.
       */
      public com.google.protobuf.ByteString getArgs(int index) {
        return args_.get(index);
      }
      /**
       * <code>repeated bytes args = 3;</code>
       * @param index The index to set the value at.
       * @param value The args to set.
       * @return This builder for chaining.
       */
      public Builder setArgs(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureArgsIsMutable();
        args_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes args = 3;</code>
       * @param value The args to add.
       * @return This builder for chaining.
       */
      public Builder addArgs(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureArgsIsMutable();
        args_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes args = 3;</code>
       * @param values The args to add.
       * @return This builder for chaining.
       */
      public Builder addAllArgs(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, args_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes args = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearArgs() {
        args_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.ByteString> kwargs_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
          internalGetKwargs() {
        if (kwargs_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              KwargsDefaultEntryHolder.defaultEntry);
        }
        return kwargs_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
          internalGetMutableKwargs() {
        if (kwargs_ == null) {
          kwargs_ = com.google.protobuf.MapField.newMapField(
              KwargsDefaultEntryHolder.defaultEntry);
        }
        if (!kwargs_.isMutable()) {
          kwargs_ = kwargs_.copy();
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return kwargs_;
      }
      public int getKwargsCount() {
        return internalGetKwargs().getMap().size();
      }
      /**
       * <pre>
       * reserved for scala / python etc.
       * </pre>
       *
       * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
       */
      @java.lang.Override
      public boolean containsKwargs(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetKwargs().getMap().containsKey(key);
      }
      /**
       * Use {@link #getKwargsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getKwargs() {
        return getKwargsMap();
      }
      /**
       * <pre>
       * reserved for scala / python etc.
       * </pre>
       *
       * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getKwargsMap() {
        return internalGetKwargs().getMap();
      }
      /**
       * <pre>
       * reserved for scala / python etc.
       * </pre>
       *
       * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
       */
      @java.lang.Override
      public /* nullable */
com.google.protobuf.ByteString getKwargsOrDefault(
          java.lang.String key,
          /* nullable */
com.google.protobuf.ByteString defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            internalGetKwargs().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * reserved for scala / python etc.
       * </pre>
       *
       * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKwargsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            internalGetKwargs().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearKwargs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableKwargs().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * reserved for scala / python etc.
       * </pre>
       *
       * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
       */
      public Builder removeKwargs(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableKwargs().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
          getMutableKwargs() {
        bitField0_ |= 0x00000008;
        return internalGetMutableKwargs().getMutableMap();
      }
      /**
       * <pre>
       * reserved for scala / python etc.
       * </pre>
       *
       * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
       */
      public Builder putKwargs(
          java.lang.String key,
          com.google.protobuf.ByteString value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableKwargs().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       * reserved for scala / python etc.
       * </pre>
       *
       * <code>map&lt;string, bytes&gt; kwargs = 4;</code>
       */
      public Builder putAllKwargs(
          java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
        internalGetMutableKwargs().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000008;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.webank.eggroll.core.command.CommandRequest)
    }

    // @@protoc_insertion_point(class_scope:com.webank.eggroll.core.command.CommandRequest)
    private static final com.webank.eggroll.core.command.Command.CommandRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.webank.eggroll.core.command.Command.CommandRequest();
    }

    public static com.webank.eggroll.core.command.Command.CommandRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommandRequest>
        PARSER = new com.google.protobuf.AbstractParser<CommandRequest>() {
      @java.lang.Override
      public CommandRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CommandRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommandRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.webank.eggroll.core.command.Command.CommandRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommandResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.webank.eggroll.core.command.CommandResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
     * @return The request.
     */
    com.webank.eggroll.core.command.Command.CommandRequest getRequest();
    /**
     * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
     */
    com.webank.eggroll.core.command.Command.CommandRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>repeated bytes results = 3;</code>
     * @return A list containing the results.
     */
    java.util.List<com.google.protobuf.ByteString> getResultsList();
    /**
     * <code>repeated bytes results = 3;</code>
     * @return The count of results.
     */
    int getResultsCount();
    /**
     * <code>repeated bytes results = 3;</code>
     * @param index The index of the element to return.
     * @return The results at the given index.
     */
    com.google.protobuf.ByteString getResults(int index);

    /**
     * <code>string code = 4;</code>
     * @return The code.
     */
    java.lang.String getCode();
    /**
     * <code>string code = 4;</code>
     * @return The bytes for code.
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>string msg = 5;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 5;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code com.webank.eggroll.core.command.CommandResponse}
   */
  public static final class CommandResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.webank.eggroll.core.command.CommandResponse)
      CommandResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommandResponse.newBuilder() to construct.
    private CommandResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandResponse() {
      id_ = "";
      results_ = java.util.Collections.emptyList();
      code_ = "";
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CommandResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.webank.eggroll.core.command.Command.CommandResponse.class, com.webank.eggroll.core.command.Command.CommandResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    private com.webank.eggroll.core.command.Command.CommandRequest request_;
    /**
     * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
     * @return The request.
     */
    @java.lang.Override
    public com.webank.eggroll.core.command.Command.CommandRequest getRequest() {
      return request_ == null ? com.webank.eggroll.core.command.Command.CommandRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
     */
    @java.lang.Override
    public com.webank.eggroll.core.command.Command.CommandRequestOrBuilder getRequestOrBuilder() {
      return request_ == null ? com.webank.eggroll.core.command.Command.CommandRequest.getDefaultInstance() : request_;
    }

    public static final int RESULTS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.ByteString> results_;
    /**
     * <code>repeated bytes results = 3;</code>
     * @return A list containing the results.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getResultsList() {
      return results_;
    }
    /**
     * <code>repeated bytes results = 3;</code>
     * @return The count of results.
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated bytes results = 3;</code>
     * @param index The index of the element to return.
     * @return The results at the given index.
     */
    public com.google.protobuf.ByteString getResults(int index) {
      return results_.get(index);
    }

    public static final int CODE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object code_ = "";
    /**
     * <code>string code = 4;</code>
     * @return The code.
     */
    @java.lang.Override
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <code>string code = 4;</code>
     * @return The bytes for code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object msg_ = "";
    /**
     * <code>string msg = 5;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 5;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (request_ != null) {
        output.writeMessage(2, getRequest());
      }
      for (int i = 0; i < results_.size(); i++) {
        output.writeBytes(3, results_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msg_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRequest());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < results_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(results_.get(i));
        }
        size += dataSize;
        size += 1 * getResultsList().size();
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.webank.eggroll.core.command.Command.CommandResponse)) {
        return super.equals(obj);
      }
      com.webank.eggroll.core.command.Command.CommandResponse other = (com.webank.eggroll.core.command.Command.CommandResponse) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (!getResultsList()
          .equals(other.getResultsList())) return false;
      if (!getCode()
          .equals(other.getCode())) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.webank.eggroll.core.command.Command.CommandResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.webank.eggroll.core.command.Command.CommandResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.webank.eggroll.core.command.Command.CommandResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.webank.eggroll.core.command.CommandResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.webank.eggroll.core.command.CommandResponse)
        com.webank.eggroll.core.command.Command.CommandResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.webank.eggroll.core.command.Command.CommandResponse.class, com.webank.eggroll.core.command.Command.CommandResponse.Builder.class);
      }

      // Construct using com.webank.eggroll.core.command.Command.CommandResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        request_ = null;
        if (requestBuilder_ != null) {
          requestBuilder_.dispose();
          requestBuilder_ = null;
        }
        results_ = java.util.Collections.emptyList();
        code_ = "";
        msg_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.webank.eggroll.core.command.Command.internal_static_com_webank_eggroll_core_command_CommandResponse_descriptor;
      }

      @java.lang.Override
      public com.webank.eggroll.core.command.Command.CommandResponse getDefaultInstanceForType() {
        return com.webank.eggroll.core.command.Command.CommandResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.webank.eggroll.core.command.Command.CommandResponse build() {
        com.webank.eggroll.core.command.Command.CommandResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.webank.eggroll.core.command.Command.CommandResponse buildPartial() {
        com.webank.eggroll.core.command.Command.CommandResponse result = new com.webank.eggroll.core.command.Command.CommandResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.webank.eggroll.core.command.Command.CommandResponse result) {
        if (((bitField0_ & 0x00000004) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.results_ = results_;
      }

      private void buildPartial0(com.webank.eggroll.core.command.Command.CommandResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.request_ = requestBuilder_ == null
              ? request_
              : requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.msg_ = msg_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.webank.eggroll.core.command.Command.CommandResponse) {
          return mergeFrom((com.webank.eggroll.core.command.Command.CommandResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.webank.eggroll.core.command.Command.CommandResponse other) {
        if (other == com.webank.eggroll.core.command.Command.CommandResponse.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getRequestFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureResultsIsMutable();
                results_.add(v);
                break;
              } // case 26
              case 34: {
                code_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                msg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.webank.eggroll.core.command.Command.CommandRequest request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.webank.eggroll.core.command.Command.CommandRequest, com.webank.eggroll.core.command.Command.CommandRequest.Builder, com.webank.eggroll.core.command.Command.CommandRequestOrBuilder> requestBuilder_;
      /**
       * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
       * @return The request.
       */
      public com.webank.eggroll.core.command.Command.CommandRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.webank.eggroll.core.command.Command.CommandRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
       */
      public Builder setRequest(com.webank.eggroll.core.command.Command.CommandRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
       */
      public Builder setRequest(
          com.webank.eggroll.core.command.Command.CommandRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
       */
      public Builder mergeRequest(com.webank.eggroll.core.command.Command.CommandRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            request_ != null &&
            request_ != com.webank.eggroll.core.command.Command.CommandRequest.getDefaultInstance()) {
            getRequestBuilder().mergeFrom(value);
          } else {
            request_ = value;
          }
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
       */
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        request_ = null;
        if (requestBuilder_ != null) {
          requestBuilder_.dispose();
          requestBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
       */
      public com.webank.eggroll.core.command.Command.CommandRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
       */
      public com.webank.eggroll.core.command.Command.CommandRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.webank.eggroll.core.command.Command.CommandRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.com.webank.eggroll.core.command.CommandRequest request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.webank.eggroll.core.command.Command.CommandRequest, com.webank.eggroll.core.command.Command.CommandRequest.Builder, com.webank.eggroll.core.command.Command.CommandRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.webank.eggroll.core.command.Command.CommandRequest, com.webank.eggroll.core.command.Command.CommandRequest.Builder, com.webank.eggroll.core.command.Command.CommandRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private java.util.List<com.google.protobuf.ByteString> results_ = java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          results_ = new java.util.ArrayList<com.google.protobuf.ByteString>(results_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <code>repeated bytes results = 3;</code>
       * @return A list containing the results.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getResultsList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(results_) : results_;
      }
      /**
       * <code>repeated bytes results = 3;</code>
       * @return The count of results.
       */
      public int getResultsCount() {
        return results_.size();
      }
      /**
       * <code>repeated bytes results = 3;</code>
       * @param index The index of the element to return.
       * @return The results at the given index.
       */
      public com.google.protobuf.ByteString getResults(int index) {
        return results_.get(index);
      }
      /**
       * <code>repeated bytes results = 3;</code>
       * @param index The index to set the value at.
       * @param value The results to set.
       * @return This builder for chaining.
       */
      public Builder setResults(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes results = 3;</code>
       * @param value The results to add.
       * @return This builder for chaining.
       */
      public Builder addResults(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes results = 3;</code>
       * @param values The results to add.
       * @return This builder for chaining.
       */
      public Builder addAllResults(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes results = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearResults() {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>string code = 4;</code>
       * @return The code.
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string code = 4;</code>
       * @return The bytes for code.
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string code = 4;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        code_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        code_ = getDefaultInstance().getCode();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string code = 4;</code>
       * @param value The bytes for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        code_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 5;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 5;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 5;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        msg_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        msg_ = getDefaultInstance().getMsg();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 5;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        msg_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.webank.eggroll.core.command.CommandResponse)
    }

    // @@protoc_insertion_point(class_scope:com.webank.eggroll.core.command.CommandResponse)
    private static final com.webank.eggroll.core.command.Command.CommandResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.webank.eggroll.core.command.Command.CommandResponse();
    }

    public static com.webank.eggroll.core.command.Command.CommandResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommandResponse>
        PARSER = new com.google.protobuf.AbstractParser<CommandResponse>() {
      @java.lang.Override
      public CommandResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CommandResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommandResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.webank.eggroll.core.command.Command.CommandResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_webank_eggroll_core_command_CommandRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_webank_eggroll_core_command_CommandRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_webank_eggroll_core_command_CommandRequest_KwargsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_webank_eggroll_core_command_CommandRequest_KwargsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_webank_eggroll_core_command_CommandResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_webank_eggroll_core_command_CommandResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025eggroll/command.proto\022\037com.webank.eggr" +
      "oll.core.command\"\263\001\n\016CommandRequest\022\n\n\002i" +
      "d\030\001 \001(\t\022\013\n\003uri\030\002 \001(\t\022\014\n\004args\030\003 \003(\014\022K\n\006kw" +
      "args\030\004 \003(\0132;.com.webank.eggroll.core.com" +
      "mand.CommandRequest.KwargsEntry\032-\n\013Kwarg" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"\213" +
      "\001\n\017CommandResponse\022\n\n\002id\030\001 \001(\t\022@\n\007reques" +
      "t\030\002 \001(\0132/.com.webank.eggroll.core.comman" +
      "d.CommandRequest\022\017\n\007results\030\003 \003(\014\022\014\n\004cod" +
      "e\030\004 \001(\t\022\013\n\003msg\030\005 \001(\t2\360\001\n\016CommandService\022" +
      "i\n\004call\022/.com.webank.eggroll.core.comman" +
      "d.CommandRequest\0320.com.webank.eggroll.co" +
      "re.command.CommandResponse\022s\n\ncallStream" +
      "\022/.com.webank.eggroll.core.command.Comma" +
      "ndRequest\0320.com.webank.eggroll.core.comm" +
      "and.CommandResponse(\0010\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_webank_eggroll_core_command_CommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_webank_eggroll_core_command_CommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_webank_eggroll_core_command_CommandRequest_descriptor,
        new java.lang.String[] { "Id", "Uri", "Args", "Kwargs", });
    internal_static_com_webank_eggroll_core_command_CommandRequest_KwargsEntry_descriptor =
      internal_static_com_webank_eggroll_core_command_CommandRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_webank_eggroll_core_command_CommandRequest_KwargsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_webank_eggroll_core_command_CommandRequest_KwargsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_webank_eggroll_core_command_CommandResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_webank_eggroll_core_command_CommandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_webank_eggroll_core_command_CommandResponse_descriptor,
        new java.lang.String[] { "Id", "Request", "Results", "Code", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
