# -*- coding: utf-8 -*-
#
#  Copyright 2019 The FATE Authors. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import storage_basic_pb2 as storage__basic__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kv.proto',
  package='com.webank.ai.fate.api.eggroll.storage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08kv.proto\x12&com.webank.ai.fate.api.eggroll.storage\x1a\x13storage-basic.proto\"9\n\x05Range\x12\r\n\x05start\x18\x01 \x01(\x0c\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x0c\x12\x14\n\x0cminChunkSize\x18\x03 \x01(\x03\"\x07\n\x05\x45mpty\"%\n\x07Operand\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x16\n\x05\x43ount\x12\r\n\x05value\x18\x01 \x01(\x03\"x\n\x0f\x43reateTableInfo\x12N\n\x0estorageLocator\x18\x01 \x01(\x0b\x32\x36.com.webank.ai.fate.api.eggroll.storage.StorageLocator\x12\x15\n\rfragmentCount\x18\x02 \x01(\x05\x32\xd2\x08\n\tKVService\x12\x82\x01\n\x0e\x63reateIfAbsent\x12\x37.com.webank.ai.fate.api.eggroll.storage.CreateTableInfo\x1a\x37.com.webank.ai.fate.api.eggroll.storage.CreateTableInfo\x12\x65\n\x03put\x12/.com.webank.ai.fate.api.eggroll.storage.Operand\x1a-.com.webank.ai.fate.api.eggroll.storage.Empty\x12o\n\x0bputIfAbsent\x12/.com.webank.ai.fate.api.eggroll.storage.Operand\x1a/.com.webank.ai.fate.api.eggroll.storage.Operand\x12j\n\x06putAll\x12/.com.webank.ai.fate.api.eggroll.storage.Operand\x1a-.com.webank.ai.fate.api.eggroll.storage.Empty(\x01\x12j\n\x06\x64\x65lOne\x12/.com.webank.ai.fate.api.eggroll.storage.Operand\x1a/.com.webank.ai.fate.api.eggroll.storage.Operand\x12g\n\x03get\x12/.com.webank.ai.fate.api.eggroll.storage.Operand\x1a/.com.webank.ai.fate.api.eggroll.storage.Operand\x12k\n\x07iterate\x12-.com.webank.ai.fate.api.eggroll.storage.Range\x1a/.com.webank.ai.fate.api.eggroll.storage.Operand0\x01\x12g\n\x07\x64\x65stroy\x12-.com.webank.ai.fate.api.eggroll.storage.Empty\x1a-.com.webank.ai.fate.api.eggroll.storage.Empty\x12j\n\ndestroyAll\x12-.com.webank.ai.fate.api.eggroll.storage.Empty\x1a-.com.webank.ai.fate.api.eggroll.storage.Empty\x12\x65\n\x05\x63ount\x12-.com.webank.ai.fate.api.eggroll.storage.Empty\x1a-.com.webank.ai.fate.api.eggroll.storage.Countb\x06proto3')
  ,
  dependencies=[storage__basic__pb2.DESCRIPTOR,])




_RANGE = _descriptor.Descriptor(
  name='Range',
  full_name='com.webank.ai.fate.api.eggroll.storage.Range',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='com.webank.ai.fate.api.eggroll.storage.Range.start', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='com.webank.ai.fate.api.eggroll.storage.Range.end', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minChunkSize', full_name='com.webank.ai.fate.api.eggroll.storage.Range.minChunkSize', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=130,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='com.webank.ai.fate.api.eggroll.storage.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=139,
)


_OPERAND = _descriptor.Descriptor(
  name='Operand',
  full_name='com.webank.ai.fate.api.eggroll.storage.Operand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.webank.ai.fate.api.eggroll.storage.Operand.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.webank.ai.fate.api.eggroll.storage.Operand.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=178,
)


_COUNT = _descriptor.Descriptor(
  name='Count',
  full_name='com.webank.ai.fate.api.eggroll.storage.Count',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='com.webank.ai.fate.api.eggroll.storage.Count.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=202,
)


_CREATETABLEINFO = _descriptor.Descriptor(
  name='CreateTableInfo',
  full_name='com.webank.ai.fate.api.eggroll.storage.CreateTableInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='storageLocator', full_name='com.webank.ai.fate.api.eggroll.storage.CreateTableInfo.storageLocator', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fragmentCount', full_name='com.webank.ai.fate.api.eggroll.storage.CreateTableInfo.fragmentCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=324,
)

_CREATETABLEINFO.fields_by_name['storageLocator'].message_type = storage__basic__pb2._STORAGELOCATOR
DESCRIPTOR.message_types_by_name['Range'] = _RANGE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Operand'] = _OPERAND
DESCRIPTOR.message_types_by_name['Count'] = _COUNT
DESCRIPTOR.message_types_by_name['CreateTableInfo'] = _CREATETABLEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Range = _reflection.GeneratedProtocolMessageType('Range', (_message.Message,), dict(
  DESCRIPTOR = _RANGE,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.eggroll.storage.Range)
  ))
_sym_db.RegisterMessage(Range)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.eggroll.storage.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Operand = _reflection.GeneratedProtocolMessageType('Operand', (_message.Message,), dict(
  DESCRIPTOR = _OPERAND,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.eggroll.storage.Operand)
  ))
_sym_db.RegisterMessage(Operand)

Count = _reflection.GeneratedProtocolMessageType('Count', (_message.Message,), dict(
  DESCRIPTOR = _COUNT,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.eggroll.storage.Count)
  ))
_sym_db.RegisterMessage(Count)

CreateTableInfo = _reflection.GeneratedProtocolMessageType('CreateTableInfo', (_message.Message,), dict(
  DESCRIPTOR = _CREATETABLEINFO,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.fate.api.eggroll.storage.CreateTableInfo)
  ))
_sym_db.RegisterMessage(CreateTableInfo)



_KVSERVICE = _descriptor.ServiceDescriptor(
  name='KVService',
  full_name='com.webank.ai.fate.api.eggroll.storage.KVService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=327,
  serialized_end=1433,
  methods=[
  _descriptor.MethodDescriptor(
    name='createIfAbsent',
    full_name='com.webank.ai.fate.api.eggroll.storage.KVService.createIfAbsent',
    index=0,
    containing_service=None,
    input_type=_CREATETABLEINFO,
    output_type=_CREATETABLEINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='put',
    full_name='com.webank.ai.fate.api.eggroll.storage.KVService.put',
    index=1,
    containing_service=None,
    input_type=_OPERAND,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='putIfAbsent',
    full_name='com.webank.ai.fate.api.eggroll.storage.KVService.putIfAbsent',
    index=2,
    containing_service=None,
    input_type=_OPERAND,
    output_type=_OPERAND,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='putAll',
    full_name='com.webank.ai.fate.api.eggroll.storage.KVService.putAll',
    index=3,
    containing_service=None,
    input_type=_OPERAND,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delOne',
    full_name='com.webank.ai.fate.api.eggroll.storage.KVService.delOne',
    index=4,
    containing_service=None,
    input_type=_OPERAND,
    output_type=_OPERAND,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='com.webank.ai.fate.api.eggroll.storage.KVService.get',
    index=5,
    containing_service=None,
    input_type=_OPERAND,
    output_type=_OPERAND,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='iterate',
    full_name='com.webank.ai.fate.api.eggroll.storage.KVService.iterate',
    index=6,
    containing_service=None,
    input_type=_RANGE,
    output_type=_OPERAND,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='destroy',
    full_name='com.webank.ai.fate.api.eggroll.storage.KVService.destroy',
    index=7,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='destroyAll',
    full_name='com.webank.ai.fate.api.eggroll.storage.KVService.destroyAll',
    index=8,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='count',
    full_name='com.webank.ai.fate.api.eggroll.storage.KVService.count',
    index=9,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_COUNT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KVSERVICE)

DESCRIPTOR.services_by_name['KVService'] = _KVSERVICE

# @@protoc_insertion_point(module_scope)
