data_guest: "breast_hetero_guest"
data_host: "breast_hetero_host"
idx: "id"
label_name: "y"
epochs: 15
init_param:
  fit_intercept: True
  method: "uniform"
  random_state: 42
learning_rate_scheduler:
  method: "constant"
  scheduler_params:
    factor: 1.0
    total_iters: 100
optimizer:
  method: "rmsprop"
  penalty: "l1"
  optimizer_params:
    lr: 0.5
  alpha: 0.1
batch_size: null
early_stop: "diff"