data_guest: "examples/data/breast_hetero_guest.csv"
data_host: "examples/data/breast_hetero_host.csv"
idx: "id"
label_name: "y"
epochs: 30
fit_intercept: True
method: "rmsprop"
penalty: "L2"
eta0: 0.1
alpha: 0.05
batch_size: 5000