data_guest: "examples/data/breast_hetero_guest.csv"
data_host: "examples/data/breast_hetero_host.csv"
idx: "id"
label_name: "y"
epochs: 30
init_param:
  fit_intercept: True
  method: "zeros"
learning_rate_scheduler:
  method: "constant"
  scheduler_params:
    factor: 1.0
    total_iters: 100
optimizer:
  method: "rmsprop"
  penalty: "L2"
  optimizer_params:
    lr: 0.1
  alpha: 0.5
batch_size: 5000
early_stop: "diff"