data_guest: "default_credit_hetero_guest"
data_host: "default_credit_hetero_host"
idx: "id"
label_name: "y"
epochs: 6
init_param:
  fit_intercept: True
  method: "zeros"
  random_state: 42
learning_rate_scheduler:
  method: "linear"
  scheduler_params:
    start_factor: 0.7
    total_iters: 1000
optimizer:
  method: "rmsprop"
  penalty: "L2"
  alpha: 0.01
  optimizer_params:
    lr: 0.1
batch_size: 1000
early_stop: "diff"