data_guest: "default_credit_hetero_guest"
data_host: "default_credit_hetero_host"
idx: "id"
label_name: "y"
epochs: 30
init_param:
  fit_intercept: True
  method: "zeros"
  random_state: 42
learning_rate_scheduler:
  method: "constant"
  scheduler_params:
    factor: 1.0
    total_iters: 10000
optimizer:
  method: "rmsprop"
  penalty: "L2"
  alpha: 0.001
  optimizer_params:
    lr: 0.15
batch_size: 3200
early_stop: "diff"