data_guest: "examples/data/epsilon_5k_hetero_guest.csv"
data_host: "examples/data/epsilon_5k_hetero_host.csv"
idx: "id"
label_name: "y"
epochs: 10
fit_intercept: True
method: "rmsprop"
penalty: "l2"
eta0: 0.1
alpha: 0.001
batch_size: 5000