data_guest: "epsilon_5k_hetero_guest"
data_host: "epsilon_5k_hetero_host"
idx: "id"
label_name: "y"
epochs: 8
batch_size: 2200
init_param:
  fit_intercept: True
  method: "random"
  random_state: 42
learning_rate_scheduler:
  method: "linear"
  scheduler_params:
    start_factor: 0.7
    total_iters: 1000
optimizer:
  method: "adam"
  penalty: "L2"
  alpha: 0.0001
  optimizer_params:
    lr: 0.43
early_stop: "diff"