data_guest: "give_credit_hetero_guest"
data_host: "give_credit_hetero_host"
idx: "id"
label_name: "y"
epochs: 6
init_param:
  fit_intercept: True
  method: "zeros"
learning_rate_scheduler:
  method: "linear"
  scheduler_params:
    factor: 0.7
    total_iters: 1000
optimizer:
  method: "adam"
  penalty: "L2"
  alpha: 10
  optimizer_params:
    lr: 0.2
batch_size: 5500
early_stop: "diff"