data_guest: "give_credit_hetero_guest"
data_host: "give_credit_hetero_host"
idx: "id"
label_name: "y"
epochs: 6
init_param:
  fit_intercept: True
  method: "zeros"
learning_rate_scheduler:
  method: "constant"
  scheduler_params:
    factor: 1.0
    total_iters: 100
optimizer:
  method: "adam"
  penalty: "L2"
  optimizer_params:
    lr: 0.15
batch_size: 550
early_stop: "diff"