data_guest: "vehicle_scale_hetero_guest"
data_host: "vehicle_scale_hetero_host"
idx: "id"
label_name: "y"
epochs: 10
init_param:
  fit_intercept: True
  method: "random_uniform"
  random_state: 42
learning_rate_scheduler:
  method: "linear"
  scheduler_params:
    start_factor: 0.7
    total_iters: 800
optimizer:
  method: "adam"
  penalty: "L2"
  alpha: 0.000001
  optimizer_params:
    lr: 0.3
batch_size: 18
early_stop: "diff"
task_cores: null
timeout: 3600
learning_rate: 0.3