data_guest: "examples/data/vehicle_scale_hetero_guest.csv"
data_host: "examples/data/vehicle_scale_hetero_host.csv"
idx: "id"
label_name: "y"
epochs: 20
init_param:
  fit_intercept: True
  method: "zeros"
learning_rate_scheduler:
  method: "constant"
  scheduler_params:
    lr: 0.3
    factor: 1.0
    total_iters: 800
optimizer:
  method: "adam"
  penalty: "L2"
batch_size: 16
early_stop: "diff"