data_guest: "examples/data/epsilon_5k_hetero_guest.csv"
data_host: "examples/data/epsilon_5k_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
epochs: 30
learning_rate_scheduler:
  method: "constant"
  scheduler_params:
    lr: 0.15
    factor: 1.0
    total_iters: 800
optimizer:
  method: "rmsprop"
batch_size: 5000
early_stop: "diff"