data_guest: "examples/data/give_credit_hetero_guest.csv"
data_host: "examples/data/give_credit_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
epochs: 6
learning_rate_scheduler:
  method: "constant"
  scheduler_params:
    lr: 0.15
    factor: 1.0
    total_iters: 100
optimizer:
  method: "adam"
batch_size: 550
early_stop: "diff"