dag:
  scheduler_party_id: 9999
  parameters:
    inherit:
      job_id: 202211141733532889390
      tasks:
      - reader_0
      - lr_0
    task_parallelism: 1
    federated_status_collect_type: PUSH
    auto_retries: 1
    model_id: demo
    model_version: demo
    task:
      task_cores: 8
      engine:
        computing:
          partitions: 8
          type: eggroll
          metadata:
            eggroll.session.processors.per.node: 4
        federation:
          type: pulsar
          metadata:
            max_message_size: 104857
            topic_ttl: 1
  stage: train
  parties:
    - role: guest
      party_id:
        -9999
        -10000
  party_tasks:
    guest_9999:
      parties:
      - party_id: 9999
        role: guest
      tasks:
        reader_0:
          inputs:
            parameters:
              path: examples/data/breast_hetero_guest.csv
    host_10000:
      parties:
      - party_id: 10000
        role: host
      tasks:
        reader_0:
          inputs:
            parameters:
              path: examples/data/breast_hetero_host.csv
  tasks:
    lr_0:
      stage:
      component_ref: hetero_lr
      dependent_tasks:
      - reader_0
      inputs:
        artifacts:
          train_data:
            task_output_artifact:
              producer_task: reader_0
              artifact_key: data
          model:
            zoo:
              model_id: xxxx
              model_version: xxx
              producer_task: lr_0
              artifact_key: model
              output_artifact_key: model
              metadata:
                model_id:
        parameters:
          learning_rate: 0.1
          max_iter: 10
    reader_0:
      component_ref: reader
      parties:
      - party_id: 9999
        role: guest
      - party_id: 10000
        role: host
      task_info:
        name: reader_0
schema_version: 2.0.0.alpha

