dag:
  scheduler_party:
    party_id: 9999
  job_parameters:
    inheritance_parameters:
      job_id: 202211141733532889390
      components:
      - reader_0
      - lr_0
    task_parallelism: 1
    federated_status_collect_type: PUSH
    auto_retries: 1
    model_id: demo
    model_version: demo
  task_parameters:
    task_cores: 8
    engine_parameters:
      computing:
        partitions: 8
        eggroll:
          eggroll.session.processors.per.node: 4
        spark:
          num-executors: 2
          executor-cores: 2
      federation:
        pulsar:
          max_message_size: 104857
          topic_ttl: 1
        rabbitmq:
          max_message_size: 1048576
  stage: train
  parties:
  - party_id: 10001
    role: arbiter
  - party_id: 9999
    role: guest
  - party_id: 10000
    role: host
  party_tasks:
    guest_9999:
      parties:
      - party_id: 9999
        role: guest
      tasks:
        reader_0:
          inputs:
            parameters:
              path: examples/data/breast_hetero_guest.csv
    host_10000:
      parties:
      - party_id: 10000
        role: host
      tasks:
        reader_0:
          inputs:
            parameters:
              path: examples/data/breast_hetero_host.csv
    task_parameters: {}
  tasks:
    lr_0:
      component_ref: hetero_lr
      dependent_tasks:
      - reader_0
      inputs:
        artifacts:
          train_data:
            task_output_artifact:
              producer_task: reader_0
              output_artifact_key: data
        parameters:
          learning_rate: 0.1
          max_iter: 10
      parties:
      - party_id: 10001
        role: arbiter
      - party_id: 9999
        role: guest
      - party_id: 10000
        role: host
      task_info:
        name: lr_0
    reader_0:
      component_ref: reader
      parties:
      - party_id: 9999
        role: guest
      - party_id: 10000
        role: host
      task_info:
        name: reader_0
schema_version: 2.0.0.alpha

