dag:
  conf:
    task_parallelism: 1
  parties:
  - party_id:
    - '9999'
    role: guest
  - party_id:
    - '10000'
    - '10001'
    role: host
  - party_id:
    - '10001'
    role: arbiter
  party_tasks:
    guest_9999:
      parties:
      - party_id:
        - '9999'
        role: guest
      tasks:
        reader_0:
          conf:
            exec_env: docker
          inputs:
            parameters:
              delimiter: ','
              dtype: float32
              format: csv
              id_name: id
              label_name: y
              label_type: float32
              path: examples/data/breast_hetero_guest.csv
    host_10000:
      parties:
      - party_id:
        - '10000'
        role: host
      tasks:
        reader_0:
          inputs:
            parameters:
              delimiter: ','
              dtype: float32
              format: csv
              id_name: id
              label_name: null
              path: examples/data/breast_hetero_host.csv
    host_10001:
      parties:
      - party_id:
        - '10001'
        role: host
      tasks:
        reader_0:
          inputs:
            parameters:
              delimiter: ','
              dtype: float32
              format: csv
              id_name: id
              label_name: null
              path: examples/data/breast_hetero_host.csv
  scheduler_party_id: '10001'
  stage: train
  tasks:
    feature_scale_0:
      component_ref: feature_scale
      dependent_tasks:
      - intersection_0
      inputs:
        artifacts:
          train_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: intersection_0
        parameters:
          method: standard
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        - '10001'
        role: host
    feature_scale_1:
      component_ref: feature_scale
      dependent_tasks:
      - intersection_1
      - feature_scale_0
      inputs:
        artifacts:
          input_model:
            task_output_artifact:
              output_artifact_key: output_model
              producer_task: feature_scale_0
          test_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: intersection_1
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        - '10001'
        role: host
      stage: predict
    intersection_0:
      component_ref: intersection
      dependent_tasks:
      - reader_0
      inputs:
        artifacts:
          input_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: reader_0
        parameters:
          method: raw
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        - '10001'
        role: host
      stage: default
    intersection_1:
      component_ref: intersection
      dependent_tasks:
      - reader_0
      inputs:
        artifacts:
          input_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: reader_0
        parameters:
          method: raw
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        - '10001'
        role: host
      stage: default
    lr_0:
      component_ref: hetero_lr
      dependent_tasks:
      - feature_scale_0
      inputs:
        artifacts:
          train_data:
            task_output_artifact:
              output_artifact_key: train_output_data
              producer_task: feature_scale_0
        parameters:
          batch_size: -1
          max_iter: 1
    lr_1:
      component_ref: hetero_lr
      dependent_tasks:
      - lr_0
      - feature_scale_1
      inputs:
        artifacts:
          input_model:
            task_output_artifact:
              output_artifact_key: output_model
              producer_task: lr_0
          test_data:
            task_output_artifact:
              output_artifact_key: test_output_data
              producer_task: feature_scale_1
      stage: predict
    reader_0:
      component_ref: reader
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        - '10001'
        role: host
      stage: default
schema_version: 2.0.0.alpha
