dag:
  parties:
  - party_id: ['9999']
    role: guest
  - party_id: ['9999']
    role: host
  - party_id: ['9999']
    role: arbiter
  party_tasks:
    guest_9999:
      parties:
      - party_id: ['9999']
        role: guest
      tasks:
        reader_0:
          inputs:
            parameters: {delimiter: ',', dtype: float32, format: csv, id_name: id,
              label_name: y, label_type: float32, path: 'file://${abs_path_of_data_guest}'}
    host_9999:
      parties:
      - party_id: ['9999']
        role: host
      tasks:
        reader_0:
          inputs:
            parameters: {delimiter: ',', dtype: float32, format: csv, id_name: id,
              label_name: null, path: 'file://${abs_path_of_data_host}'}
  stage: train
  tasks:
    evaluation_0:
      component_ref: evaluation
      dependent_tasks: [lr_0]
      inputs:
        artifacts:
          input_data:
            task_output_artifact:
              output_artifact_key: train_output_data
              producer_task: lr_0
              roles: [guest]
      parties:
      - party_id: ['9999']
        role: guest
      stage: default
    feature_scale_0:
      component_ref: feature_scale
      dependent_tasks: [intersection_0]
      inputs:
        artifacts:
          train_data:
            task_output_artifact: {output_artifact_key: output_data, producer_task: intersection_0}
        parameters: {method: standard}
      parties:
      - party_id: ['9999']
        role: guest
      - party_id: ['9999']
        role: host
    feature_scale_1:
      component_ref: feature_scale
      dependent_tasks: [intersection_1, feature_scale_0]
      inputs:
        artifacts:
          input_model:
            task_output_artifact: {output_artifact_key: output_model, producer_task: feature_scale_0}
          test_data:
            task_output_artifact: {output_artifact_key: output_data, producer_task: intersection_1}
      parties:
      - party_id: ['9999']
        role: guest
      - party_id: ['9999']
        role: host
      stage: predict
    intersection_0:
      component_ref: intersection
      dependent_tasks: [reader_0]
      inputs:
        artifacts:
          input_data:
            task_output_artifact: {output_artifact_key: output_data, producer_task: reader_0}
        parameters: {method: raw}
      parties:
      - party_id: ['9999']
        role: guest
      - party_id: ['9999']
        role: host
      stage: default
    intersection_1:
      component_ref: intersection
      dependent_tasks: [reader_0]
      inputs:
        artifacts:
          input_data:
            task_output_artifact: {output_artifact_key: output_data, producer_task: reader_0}
        parameters: {method: raw}
      parties:
      - party_id: ['9999']
        role: guest
      - party_id: ['9999']
        role: host
      stage: default
    lr_0:
      component_ref: hetero_lr
      dependent_tasks: [feature_scale_0, feature_scale_1]
      inputs:
        artifacts:
          train_data:
            task_output_artifact:
              output_artifact_key: train_output_data
              producer_task: feature_scale_0
              roles: [guest, host]
          validate_data:
            task_output_artifact:
              output_artifact_key: test_output_data
              producer_task: feature_scale_1
              roles: [guest, host]
        parameters: {batch_size: 100, learning_rate: 0.01, max_iter: 1}
    reader_0:
      component_ref: reader
      parties:
      - party_id: ['9999']
        role: guest
      - party_id: ['9999']
        role: host
      stage: default
schema_version: 2.0.0.alpha
