data_guest_train: "vehicle_scale_hetero_guest"
data_guest_val: "vehicle_scale_hetero_guest"
data_host_train: "vehicle_scale_hetero_host"
data_host_val: "vehicle_scale_hetero_host"
eval_type: "multi"
task_type: "classification"
loss_func: "cross_entropy"
tree_depth: 3
tree_num: 51
learning_rate: 0.3
multi_mode: 'multi_output'
