data_guest: "examples/data/default_credit_hetero_guest.csv"
data_host: "examples/data/default_credit_hetero_host.csv"
idx: "id"
label_name: "y"
max_depth: 3
max_bin: 32
learning_rate: 0.3
n_estimators: 30
