# Copyright 2019-2022 VMware, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# you may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3'

networks:
  fate-serving-network:
    external:
      name: <fate-network>

volumes:
  data_dir_server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: <path-to-host-dir>/data/server
  data_dir_zookeeper:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: <path-to-host-dir>/data/zookeeper

services:
  serving-server:
    image: "federatedai/serving-server:${SERVING_TAG}"
    ports:
      - "8000:8000"
    volumes:
      - ./confs/serving-server/conf/serving-server.properties:/data/projects/fate-serving/serving-server/conf/serving-server.properties
      - ./data/server:/data/projects/fate-serving/serving-server/.fate
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fate-serving-network

  serving-proxy:
    image: "federatedai/serving-proxy:${SERVING_TAG}"
    ports:
      - "8059:8059"
      - "8869:8869"
    expose:
      - 8879
    volumes:
      - ./confs/serving-proxy/conf/application.properties:/data/projects/fate-serving/serving-proxy/conf/application.properties
      - ./confs/serving-proxy/conf/route_table.json:/data/projects/fate-serving/serving-proxy/conf/route_table.json
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fate-serving-network

  serving-zookeeper:
    image: "bitnami/zookeeper:3.7.0"
    user: root
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
    volumes:
      - ./data/zookeeper:/bitnami/zookeeper
      - /etc/localtime:/etc/localtime:ro
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - fate-serving-network

  serving-admin:
    image: "federatedai/serving-admin:${SERVING_TAG}"
    ports:
      - "8350:8350"
    volumes:
      - ./confs/serving-admin/conf/application.properties:/data/projects/fate-serving/serving-admin/conf/application.properties
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fate-serving-network
