guest_model:
  bottom: [13, 8]
  agg_layer: [8, 8]
  top: [8, 1]
host_model:
  bottom: [10, 8]
  agg_layer: [8, 8]
  top: [8, 1]
data_guest: "examples/data/default_credit_hetero_guest.csv"
data_host: "examples/data/default_credit_hetero_host.csv"
guest_table: "default_credit_hetero_guest"
host_table: "default_credit_hetero_host"
lr: 0.01
epochs: 10
batch_size: 1024
is_binary: True
label_name: 'y'
id_name: 'id'