data_guest: "examples/data/default_credit_hetero_guest.csv"
data_host: "examples/data/default_credit_hetero_host.csv"
idx: "id"
label_name: "y"
learning_rate: 0.02
loss: "binary_crossentropy"
tol: 0.01
batch_size: 30000
metrics: ["AUC"]
epochs: 15
bottom_layer_units: 4
interactive_layer_units: 4
top_layer_units: 1
guest_table_name: "default_credit_hetero_guest"
host_table_name: "default_credit_hetero_host"
top_act: "sigmoid"
opt: "RMSprop"
shape1: 13
shape2: 10

