data_guest: "examples/data/epsilon_5k_hetero_guest.csv"
data_host: "examples/data/epsilon_5k_hetero_host.csv"
idx: "id"
label_name: "y"
learning_rate: 0.01
loss: "binary_crossentropy"
tol: 0.01
batch_size: 5000
metrics: ["AUC"]
epochs: 100
bottom_layer_units: 4
interactive_layer_units: 4
top_layer_units: 1
guest_table_name: "epsilon_5k_hetero_guest"
host_table_name: "epsilon_5k_hetero_host"
top_act: "sigmoid"
opt: "RMSprop"
shape1: 20
shape2: 80
