name: autopep8-suggester-action
on: [pull_request]
jobs:
  linter_name:
    name: autopep8-suggester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --jobs 0 --recursive --in-place --aggressive --aggressive .
      - name: Annotate diff changes using reviewdog
        if: steps.autopep8.outputs.exit-code == 2
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: autopep8
      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1
