name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 365
          days-before-issue-close: 7
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been marked as stale because it has been open for 365 days with no activity. If this issue is still relevant or if there is new information, please feel free to update or reopen it."
          close-issue-message: "This issue was closed because it has been inactive for 7 days since being marked as stale. If this issue is still relevant or if there is new information, please feel free to update or reopen it."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
